### ISSUE TITLE
Getting Error when trying to use mod

### ISSUE THREAD

**Issue by Wolphin5** [hetima/DSP_AutoReverse#1]
When I tried to reverse the conveyor today, still having the bug.  Have 2.1.0 installed.

![image](https://user-images.githubusercontent.com/44385601/139595303-c1a6fef8-669e-4e72-888a-bc35bc711a5f.png)

**Comment by hetima** [comment]
That error is caused by DSP Belt Reverse Direction (fix update appears to have been released), not AutoReverse.

**Comment by Wolphin5** [comment]
Ooops... forgot they were seperate plugins.  thanks for the correction.
